#!/bin/sh
# Set randr
# xrandr --dpi 140

# Set key repeat rate
xset r rate 150 55

# Set mouse acceleration
xset m 1/1 0

# Restart vmtoolsd
vmware-user-suid-wrapper --no-startup-id
vmware-user

# Now start i3
i3
