-- Disable error messages display within the buffer
-- @deprecated: This is taken over by `null-ls`.
-- vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
--     vim.lsp.diagnostic.on_publish_diagnostics, {
--         virtual_text     = false,
--         update_in_insert = false,
--         signs            = function() end
--     }
-- )
